version: "3.1"
services:
  my-registry:
    image: registry:2.7.1
    volumes:
      - registry:/var/lib/registry
    ports:
      - "55000:5000"
    restart: unless-stopped
    container_name: docker-registry
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - docker-network
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - docker-network
  
  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge

volumes:
  registry:
  elasticsearch-data:
